# Generated by Django 5.0.1 on 2024-04-14 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Utilisateurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tel', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=100)),
                ('numCni', models.CharField(max_length=9)),
                ('photo', models.ImageField(upload_to='image/')),
                ('declarationPerte', models.ImageField(upload_to='image/')),
                ('certificat', models.ImageField(upload_to='image/')),
                ('acteNaissance', models.ImageField(upload_to='image/')),
                ('typeDocument', models.CharField(choices=[('primata', 'primata'), ('duplicatatUse', 'duplicatatUse'), ('duplicatatPerte', 'duplicatatPerte')], default='primata', max_length=20)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.utilisateurs')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
    ]
