# Generated by Django 5.0.1 on 2024-04-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
        migrations.AlterModelTable(
            name='document',
            table=None,
        ),
    ]
