# Generated by Django 5.0.1 on 2024-04-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_rename_documents_document_alter_document_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Utilisateurs',
            new_name='Utilisateur',
        ),
    ]
