# Generated by Django 5.0.1 on 2024-04-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_utilisateurs_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='acteNaissance',
            field=models.ImageField(default='', upload_to='image/acte'),
        ),
        migrations.AlterField(
            model_name='document',
            name='certificat',
            field=models.ImageField(upload_to='backend/image/certificat'),
        ),
        migrations.AlterField(
            model_name='document',
            name='declarationPerte',
            field=models.ImageField(default='', upload_to='backend/image/perte'),
        ),
        migrations.AlterField(
            model_name='document',
            name='photo',
            field=models.ImageField(upload_to='backend/image/photo'),
        ),
    ]
