# Generated by Django 5.0.1 on 2024-04-14 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_document_declarationperte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='numCni',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
